alias lla='ls -la'

alias mkfile='touch'
alias rmr='rm -rf'

alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'
function -() { cd -; }

alias grep='grep -ins --color'
alias rgrep='rgrep -ins --color'
alias cal='ncal -M -C'

alias df='df -h'
alias du='du -sh'

alias mnt='sudo mount'
alias unmnt='sudo umount'
alias blkid='sudo blkid'

alias rs='rsync -r --progress'
alias rsu='rsync -r -u --progress'

alias off='sudo shutdown -h now'
alias reboot='sudo reboot'
alias hibernate='sudo systemctl hibernate'
alias suspend='sudo systemctl suspend'

alias ga='git add'
alias ga.='git add .'
alias gaa='git add -A'
alias gb='git branch'
alias gbr='git branch'
alias gbc="git branch | grep \* | gawk '{ print \$2 }'"
alias gch='git checkout'
alias gco='git checkout'
alias gcb='git chechout -b'
alias gcp='git cherry-pick'
alias gcl='git clone'
alias gc='git commit'
alias gci='git commit'
alias gcf='git config'
alias gd='git diff'
alias gf='git fetch'
alias gg='git grep'
alias gi='git init'
alias gl='git log'
alias glp='git log --pretty'
alias gm='git merge'
alias gmv='git move'
alias gpl='git pull'
alias gps='git push'
alias grm='git rm'
alias gs='git status'
alias gst='git status'
alias gsh='git stash'
alias ts='tig status'

alias rl='rails'
alias rlg='rails g'
alias rld='rails d'
alias rls='rails s'
alias rlc='rails c'

alias bi='bundle install'
alias be='bundle exec'
alias bl='bundle list'
alias bu='bundle update'
alias bo='bundle outdated'
alias bc='bundle check'

alias rap='rake assets:precompile'
alias rdc='rake db:create'
alias rdd='rake db:drop'
alias rdr='rake db:rollback'
alias rdsp='rake db:setup'
alias rdsl='rake db:schema:load'
alias rdm='rake db:migrate'
alias rds='rake db:seed'
alias rr='rake routes'
alias rab='rake about'
alias rst='rake stats'
alias rno='rake notes'
alias rsp='rspec'

alias jasmine='RAILS_ENV=test bundle exec rake spec:javascript'

marks=~/.bash_bookmarks; [ -f $marks ] && . $marks
