set nocompatible
set shortmess+=I

set timeoutlen=1000
set ttimeoutlen=0

set nobackup
set noswapfile
set autoread

set history=2048
set undolevels=2048

set mouse=a
set backspace=indent,eol,start
set clipboard=unnamedplus

set t_Co=256
set background=dark
set colorcolumn=120

colorscheme desert

syntax on
filetype plugin indent on

set title
set laststatus=2
set showcmd
set ruler
set showmode
set wildmenu
set number
" set cursorline

set nowrap
set scrolloff=1
set sidescrolloff=5

set incsearch
set hlsearch
set ignorecase
set smartcase

set smarttab
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set smartindent
set shiftround

set splitright

if filereadable(expand('~/.vim/autoload/plug.vim'))
  call plug#begin('~/.vim/plugins')
  for plugin in split(expand('~/.vim/bundle/*.vim'), '\n')
    silent exec 'source ' . plugin
  endfor
  call plug#end()
endif

if lucerion#plugin#loaded('srcery-vim')
  colorscheme srcery
  let [g:srcery_bold, g:srcery_italic, g:srcery_underline] = [0, 0, 0]
endif

if executable('ag')
  let g:grep_program = 'ag'
  let g:grep_options = '--vimgrep --hidden --silent'
  let g:grep_command = g:grep_program . ' ' . g:grep_options

  silent exec 'set grepprg=' . fnameescape(g:grep_command)
endif

set statusline=%w%h\ %F\ %m
if lucerion#plugin#loaded('vim-fugitive')
  set statusline+=\ %{fugitive#statusline()}
endif
if lucerion#plugin#loaded('vim-smartword')
  set statusline+=\ %{smartword#status()}
endif
set statusline+=\ %r%=%l-%v/%L
