set nocompatible
set shortmess+=I

set nobackup
set nowritebackup
set noswapfile
set autoread

set history=128
set undolevels=1024

set mouse=a
set backspace=indent,eol,start
set clipboard=unnamedplus

set t_Co=256
set background=dark

set laststatus=2
set statusline=%w%h\ %F\ %m\ %{fugitive#statusline()}\ %r%=%l-%v/%L
set showcmd
set ruler
set showmode

set number
set nowrap
set sidescroll=20
set cursorline

set incsearch
set hlsearch
set ignorecase
set smartcase

set showmatch

set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

set splitright

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
source ~/.vim/plugins.vim
call vundle#end()
syntax on
filetype plugin indent on

colorscheme molokai

let g:ctrlp_reuse_window = 'help\|quickfix'
let g:ctrlp_working_path_mode = 'r'
let g:ctrlp_use_caching = 0
let g:ctrlp_show_hidden = 0
let g:ctrlp_extensions = ['funky']
let g:ctrlp_funky_syntax_highlight = 1

let g:ack_default_options =
  \ ' -s -H --nocolor --nogroup --nofollow --column --smart-case' .
  \ ' --ignore-dir=tmp --ignore-dir=log' .
  \ ' --ignore-file=match:/.gitignore/ --ignore-file=match:/.*.log/'

let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabContextTextOmniPrecedence = []

let g:tagbar_compact = 1

let g:vimfiler_as_default_explorer = 1
let g:vimfiler_no_default_key_mappings = 1
let g:vimfiler_expand_jump_to_first_child = 0
let g:vimfiler_ignore_pattern = ''
let g:vimfiler_time_format = '%Y-%m-%d %H:%M'
let g:vimfiler_tree_leaf_icon = ' '
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
let g:vimfiler_readonly_file_icon = 'x'

let g:extra_whitespace_ignored_filetypes =
  \ ['vimfiler', 'vimfiler:default', 'vimfiler:explorer']

let g:user_emmet_leader_key = '<C-e>'

let g:find_all_ignore = ['tmp']

let g:vim_tags_auto_generate = 0
let g:vim_tags_ctags_binary = 'ripper-tags'

au BufRead,BufNewFile *.rb setl makeprg=ruby\ %
au BufRead,BufNewFile *.html setl makeprg=google-chrome\ %

if filereadable(expand('~/.vim/mappings.vim'))
  source ~/.vim/mappings.vim
endif
